import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { DefaultLayout } from "@/components/layouts";

const jetBrains = JetBrains_Mono({
  variable: "--jetBrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trade App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetBrains.variable} antialiased`}>
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}
